Globals:
  idf_corpus: 'AQUAINT' #AQUAINT or AQUAINT-2
  lemmatized_idf: False

DocumentGroup:


Selection:
  method: 'select_lexrank'

  lexrank:
    threshold: False # can be False for continuous lexrank, otherwise float between 0 and 1 (noninclusive)
    damping: 0.4 # this also controls the degree of bias, if we have bias

    # possibilities in order of historical performance: tf_idf_similarity_matrix, tf_idf_vector_similarity_matrix, word_vector_similarity_matrix
    similarity_matrix: tf_idf_similarity_matrix

    # possibilities in order of historical performance: ir_bias, idf_weighted_vector_bias, or False (for no bias)
    #bias:  ir_bas
    bias: ir_bias


Ordering:
  use_bert: False

Realization:
  similarity_metric: 'spacy'
  similarity_threshold: 0.97
  log_realization_changes: False
  remove_quotes: True
