Globals:
  idf_corpus: 'AQUAINT' #AQUAINT or AQUAINT-2
  lemmatized_idf: False
DocumentGroup:
Selection:
  method: select_ngram
  lexrank:
    threshold: False # can be False for continuous lexrank, otherwise float between 0 and 1 (noninclusive)
    damping: 0.4 # this also controls the degree of bias, if we have bias
    # possibilities in order of historical performance: tf_idf_similarity_matrix, tf_idf_vector_similarity_matrix, word_vector_similarity_matrix
    similarity_matrix: tf_idf_similarity_matrix
    # possibilities in order of historical performance: ir_bias, idf_weighted_vector_bias, or False (for no bias)
    #bias:  ir_bas
    bias: ir_bias
  ngram:
    reweight_scheme: 'sumbasic'
    grouping: 'per_article'
    use_idf: 0
    num_sents_per_article: 2
    forward_backward: False
    length_limit: 4
    num_sents_per_glob: 1000
    unigram_weight: 0.2
    bigram_weight: 0.9
    trigram_weight: 0.00
    headline_weight: 0.0
    group_headline_weight: 0.0
    cartesian_weight: 0.0
    query_weight: 0.00
    bias_weight: 0.0 # bias
Ordering:
  use_bert: False
Realization:
  similarity_metric: 'spacy'
  similarity_threshold: 0.95
  remove_quotes: True
  remove_questions: True
  minimum_sentence_length: 4 # this is # of tokens that a sentence requires AFTER being subjected to regex, etc
  remove_full_spans_that_match: [] #add regex patterns (in quotes) separated by commas. any spans containing regex will be filtered out
  remove_subspans_that_match: [] #add regex patterns (in quotes) separated by commas. Specific regex matches will be removed
  remove_subjectless_sentences: False #Set to True to filter out ungrammatical fragments (with no subjects)
  remove_sentence_initial_terms: True
  remove_appositives: False
  remove_attributions: True
  remove_sentences_starting_with_pronouns: True
